# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        env:
          ATHENA_KEY: ${{ secrets.ATHENA_KEY }}
          ATHENA_SECRET: ${{ secrets.ATHENA_SECRET }}
          ATHENA_BASE_URL: ${{ secrets.ATHENA_BASE_URL }}
          ATHENA_AUTH_PATH: ${{ secrets.ATHENA_AUTH_PATH }}
          ATHENA_VERSION_STRING: ${{ secrets.ATHENA_VERSION_STRING }}
          ATHENA_PRACTICE_ID: ${{ secrets.ATHENA_PRACTICE_ID }}
        run: bundle exec rake